name = "SimpleSCM"
uuid = "2dda7443-35c2-4194-81f1-4a57bb7ea7b9"
authors = ["bobaronoff <bobaronoffMD@aol.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
